### ISSUE TITLE
new alpha channel support for hex colors

### ISSUE THREAD

**Issue by nathanallen** [regexps/hex-color-regex#10]
Chrome 52 now supports an "alpha" channel in hex colors:

- `#RRGGBBAA`
- `#RGBA`

Reference
- https://googlechrome.github.io/samples/css-alpha-channel/
- https://www.chromestatus.com/feature/5685348285808640

**Comment by tunnckoCore** [comment]
Thanks! I'll see what and when can do it. PRs welcome too :)
