### ISSUE TITLE
Strict comparison

### ISSUE THREAD

**Issue by btholt** [regexps/hex-color-regex#3]
Hey! I've been using this for my project [postcss-colorblind](https://github.com/btholt/postcss-colorblind) and I have a slight problem.

If you use the regex test on a URL that has an anchor link that is also a valid hex, the test method would return true.

Example:

``` javascript
var hex = require('hex-color-regex');
hex().test('url(http://www.example.com/index.html#f06d06)'); // returns true
```

The obvious fix for this is to use `^` and `$`. Would it make sense to take in a config object and have a `strict` parameter that adds `^` and `$`? If not, I'm content to fork this and use my own version. Otherwise, I'm also happy to work up a pull request if it useful.

**Comment by btholt** [comment]
BTW I opened #4 to address this. :smile:

**Comment by tunnckoCore** [comment]
@btholt sorry for the delay, I just digging `feross/standard` to add some feature (or I'll rewrite it, damn LOL - I continue to be amazed how bad the things can be written, lol) nvm.

I'll review it in a bit and thanks!

**Comment by tunnckoCore** [comment]
close, since we have pr #4 :) i'll merge asap
